pipeline {
    agent any
    tools {
	    maven "MAVEN3"
	    jdk "JDK8"
	}

    stages{

        stage('Build') {
            steps {
                sh 'mvn clean install -DskipTests'
            }

    }
}