apiVersion: apps/v1
kind: Deployment
metadata:
  name: vproapp-{{ .Release.Name }}
  labels:
    app: vproapp
spec:
  replicas: {{ .Values.vproapp.replicacount }}
  selector:
    matchLabels:
      app: vproapp
  template:
    metadata:
      labels:
        app: vproapp
    spec:
      containers:
      - name: vproapp
        image: {{ .Values.vproapp.image.repository }}:{{ .Values.vproapp.image.tag }}
        ports:
        - name: {{ .Values.vproapp.portName }}
          containerPort: {{ .Values.vproapp.containerport }}

---
apiVersion: v1
kind: Service
metadata:
  name: vproapp
spec:
  selector:
    app: vproapp
  ports:
  - port: {{ .Values.vproapp.service.port }}
    targetPort: {{ .Values.vproapp.portName }}
    {{- $svc := .Values.vproapp.service.type -}}
    {{- if eq $svc "NodePort" }}
    nodePort: {{ .Values.vproapp.service.nodePort }}
    {{- end }}
  type: {{ .Values.vproapp.service.type }}

