apiVersion: v1
kind: Service
metadata:
  name: spring-boot-app-service
spec:
  type: {{ .Values.service.type }}
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: {{ .Values.service.targetPort }}
    protocol: TCP
  selector:
    {{- include "app.labels" . | nindent 4 }}
