# Default values for vproapp 
vproapp:
  image:
    repository: dheerajlearningdocker/vprofileapp
    tag: V1
  replicacount: 2
  service:
    type: ClusterIP


# Default values for memcache
vpromc:
  image:
    repository: memcached
    tag: latest
  replicacount: 1

# Default values for rabbitmq
vprormq:
  image: 
    repository: rabbitmq
    tag: latest
  replicacount: 1


# Default values for mysql
vprodb:
  image: 
    repository: dheerajlearningdocker/vprofiledb
    tag: vprdbfix
  replicacount: 1
  persistance:
    storage: 3Gi