apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mypvc
  labels:
    type: gcp-provisioner
spec:
  storageClassName: ""
  resources:
    requests:
      storage: 3Gi
  accessModes:
    - ReadWriteOnce
